
    var basic_choropleth = new Datamap({
  element: document.getElementById("mapMonde"),
          popupTemplate: function(geography, data) { //this function should just return a string
          return '<div class="hoverinfo"><strong>' + geography.properties.name + '</strong></div>';
        },
		geographyConfig: {highlightOnHover: false},
  projection: 'mercator',
  fills: {
    defaultFill: "#BDBDBD",
    death: "#820333"
  },
  data: {
    USA: { fillKey: "death"},
    CHN: { fillKey: "death" },
    IRN: { fillKey: "death" },
    SAU: { fillKey: "death"  },
    IRQ: { fillKey: "death"  },
    SDN: { fillKey: "death"  },
	YEM: { fillKey: "death"  },
	EGY: { fillKey: "death"  },
	SOM: { fillKey: "death"  },
	JOR: { fillKey: "death"  },
	GNQ: { fillKey: "death"  },
	PAK: { fillKey: "death"  },
	AFG: { fillKey: "death"  },
	TWN: { fillKey: "death"  },
	BLR: { fillKey: "death"  },
	BHS: { fillKey: "death"  },
	BHR: { fillKey: "death"  },
	BGD: { fillKey: "death"  },
	BRB: { fillKey: "death"  },
	BWA: { fillKey: "death"  },
	TCD: { fillKey: "death"  },
	COD: { fillKey: "death"  },
	ETH: { fillKey: "death"  },
	GMB: { fillKey: "death"  },
	GTM: { fillKey: "death"  },
	GUY: { fillKey: "death"  },
	IND: { fillKey: "death"  },
	IDN: { fillKey: "death"  },
	JAM: { fillKey: "death"  },
	JPN: { fillKey: "death"  },
	KWT: { fillKey: "death"  },
	LBN: { fillKey: "death"  },
	LBY: { fillKey: "death"  },
	MYS: { fillKey: "death"  },
	NGA: { fillKey: "death"  },
	OMN: { fillKey: "death"  },
	PAK: { fillKey: "death"  },
		PSE: { fillKey: "death"  },
	QAT: { fillKey: "death"  },
	KNA: { fillKey: "death"  },
		VCT: { fillKey: "death"  },
	LCA: { fillKey: "death"  },
	SGP: { fillKey: "death"  },
		SSD: { fillKey: "death"  },
	SYR: { fillKey: "death"  },
	THA: { fillKey: "death"  },
		TTO: { fillKey: "death"  },
	UGA: { fillKey: "death"  },
	VNM: { fillKey: "death"  },
		YEM: { fillKey: "death"  },
		PRK: { fillKey: "death"  },
	ZWE: { fillKey: "death"  }
	

  }
});